redis:
  uri: redis://localhost:6379
  caches:
    entities:
      # enough to not call twice in one call, but would prevent conflicting writes
      expire-after-write: 2s
      expire-after-access: 2s
      value-serializer: io.github.wistefan.mapping.EntityVOSerializer
    subscriptions:
      expire-after-write: 14d
      expire-after-access: 14d
      value-serializer: io.github.wistefan.mapping.EntityVOSerializer