---
apiVersion: v1
kind: Service
metadata:
  name: postgis
  labels:
    app.kubernetes.io/name: postgis
    app.kubernetes.io/instance: postgis
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgis
  selector:
    app.kubernetes.io/name: postgis
    app.kubernetes.io/instance: postgis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  labels:
    app.kubernetes.io/name: postgis
    app.kubernetes.io/instance: postgis
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: postgis
      app.kubernetes.io/instance: postgis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgis
        app.kubernetes.io/instance: postgis
    spec:
      serviceAccountName: default
      containers:
        - name: postgis
          imagePullPolicy: IfNotPresent
          # as by scropio doc, no version provided
          image: "postgis/postgis"
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: "ngb"
            - name: POSTGRES_PASSWORD
              value: "ngb"
            - name: POSTGRES_DB
              value: "ngb"
---
apiVersion: v1
kind: Service
metadata:
  name: scorpio
  labels:
    app.kubernetes.io/name: scorpio
    app.kubernetes.io/instance: scorpio
spec:
  type: LoadBalancer
  ports:
    # same as orion, makes other config easier
    - port: 1026
      targetPort: 9090
      protocol: TCP
      name: scorpio
  selector:
    app.kubernetes.io/name: scorpio
    app.kubernetes.io/instance: scorpio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorpio
  labels:
    app.kubernetes.io/name: scorpio
    app.kubernetes.io/instance: scorpio
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: scorpio
      app.kubernetes.io/instance: scorpio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scorpio
        app.kubernetes.io/instance: scorpio
    spec:
      serviceAccountName: default
      containers:
        - name: scorpio
          image: "scorpiobroker/all-in-one-runner:java-4.1.11"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health
              port: 9090
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /q/health
              port: 9090
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 6
          env:
            - name: DBHOST
              value: postgis
            - name: DBPASS
              value: ngb
            - name: DBUSER
              value: ngb
            - name: POSTGRES_DB
              value: ngb
            - name: DBHOST
              value: postgis
            - name: POSTGRES_PASSWORD
              value: ngb
            - name: POSTGRES_USER
              value: ngb