micronaut:
  caches:
    entities:
      maximumSize: 1000
      # enough to not call twice in one call, but would prevent conflicting writes
      expire-after-write: 2s
      expire-after-access: 2s
    subscriptions:
      maximumSize: 1000
      expire-after-write: 14d
      expire-after-access: 14d