---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: orion-ld
  labels:
    app.kubernetes.io/name: orion-ld
    app.kubernetes.io/instance: orion-ld
spec:
  type: LoadBalancer
  ports:
    - port: 1026
      targetPort: 1026
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: orion-ld
    app.kubernetes.io/instance: orion-ld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: mongo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/instance: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/instance: mongo
    spec:
      containers:
        - name: mongo-db
          imagePullPolicy: IfNotPresent
          image: "quay.io/opencloudio/ibm-mongodb:4.0.24"
          securityContext:
            runAsUser: 999
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - bash
                - -ec
                - |
                  mongo --eval 'db.runCommand("ping").ok' 127.0.0.1:27017/test && echo 0 || echo 1
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - bash
                - -ec
                - |
                  mongo --eval 'db.runCommand("ping").ok' 127.0.0.1:27017/test && echo 0 || echo 1
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-ld
  labels:
    app.kubernetes.io/name: orion-ld
    app.kubernetes.io/instance: orion-ld
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: orion-ld
      app.kubernetes.io/instance: orion-ld
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orion-ld
        app.kubernetes.io/instance: orion-ld
    spec:
      serviceAccountName: default
      containers:
        - name: orion-ld
          imagePullPolicy: IfNotPresent
          image: "quay.io/fiware/orion-ld:1.5.1"
          ports:
            - name: http
              containerPort: 1026
              protocol: TCP
          env:
            # db
            - name: ORIONLD_MONGO_HOST
              value: mongo:27017
            - name: ORIONLD_MONGO_DB
              value: orion
            # logging
            - name: ORIONLD_LOG_LEVEL
              value: "DEBUG"
            - name: ORIONLD_TMP_TRACES
              value: "TRUE"