// GENERATED by scripts/gen-catalog.mjs from the tmforum-api repo. Do not edit by hand.
// basePaths from: all-in-one/src/main/resources/application.yaml
// resources from: api/tm-forum/<module>/api.json
// refs      from: the @AttributeGetter/@AttributeSetter annotations of the domain classes

export const GROUPS = ["Catalogue","Inventory","Ordering","Parties","Billing","Agreements","Other"];

export const APIS = [
  {
    "key": "account",
    "tmf": "TMF666",
    "label": "Account Management",
    "group": "Billing",
    "basePath": "/tmf-api/accountManagement/v4",
    "resources": [
      {
        "name": "billFormat",
        "entityType": "BillFormat",
        "urnType": "bill-format",
        "refs": []
      },
      {
        "name": "billingAccount",
        "entityType": "BillingAccount",
        "urnType": "billing-account",
        "refs": [
          {
            "field": "financialAccount",
            "many": false,
            "targets": [
              "financial-account",
              "financialAccount"
            ]
          }
        ]
      },
      {
        "name": "billingCycleSpecification",
        "entityType": "BillingCycleSpecification",
        "urnType": "billingCycleSpecification",
        "refs": []
      },
      {
        "name": "billPresentationMedia",
        "entityType": "BillPresentationMedia",
        "urnType": "bill-presentation-media",
        "refs": []
      },
      {
        "name": "financialAccount",
        "entityType": "FinancialAccount",
        "urnType": "financialAccount",
        "refs": []
      },
      {
        "name": "partyAccount",
        "entityType": "PartyAccount",
        "urnType": "party-account",
        "refs": [
          {
            "field": "financialAccount",
            "many": false,
            "targets": [
              "financial-account",
              "financialAccount"
            ]
          }
        ]
      },
      {
        "name": "settlementAccount",
        "entityType": "SettlementAccount",
        "urnType": "settlement-account",
        "refs": [
          {
            "field": "financialAccount",
            "many": false,
            "targets": [
              "financial-account",
              "financialAccount"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "agreement",
    "tmf": "TMF651",
    "label": "Agreement Management",
    "group": "Agreements",
    "basePath": "/tmf-api/agreementManagement/v4",
    "resources": [
      {
        "name": "agreement",
        "entityType": "Agreement",
        "urnType": "agreement",
        "refs": [
          {
            "field": "agreementSpecification",
            "many": false,
            "targets": [
              "agreementSpecification"
            ]
          },
          {
            "field": "associatedAgreement",
            "many": true,
            "targets": [
              "agreement"
            ]
          },
          {
            "field": "engagedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      },
      {
        "name": "agreementSpecification",
        "entityType": "AgreementSpecification",
        "urnType": "agreementSpecification",
        "refs": [
          {
            "field": "serviceCategory",
            "many": false,
            "targets": [
              "category"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "customer-bill-management",
    "tmf": "TMF678",
    "label": "Customer Bill",
    "group": "Billing",
    "basePath": "/tmf-api/customerBillManagement/v4",
    "resources": [
      {
        "name": "appliedCustomerBillingRate",
        "entityType": "AppliedCustomerBillingRate",
        "urnType": "applied-customer-billing-rate",
        "refs": [
          {
            "field": "bill",
            "many": false,
            "targets": [
              "customer-bill"
            ]
          },
          {
            "field": "billingAccount",
            "many": false,
            "targets": [
              "billing-account"
            ]
          },
          {
            "field": "product",
            "many": false,
            "targets": [
              "product"
            ]
          }
        ]
      },
      {
        "name": "customerBill",
        "entityType": "CustomerBill",
        "urnType": "customer-bill",
        "refs": [
          {
            "field": "billingAccount",
            "many": false,
            "targets": [
              "billing-account"
            ]
          },
          {
            "field": "financialAccount",
            "many": false,
            "targets": [
              "financial-account",
              "financialAccount"
            ]
          },
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "customer-management",
    "tmf": "TMF629",
    "label": "Customer Management",
    "group": "Parties",
    "basePath": "/tmf-api/customerManagement/v4",
    "resources": [
      {
        "name": "customer",
        "entityType": "Customer",
        "urnType": "customer",
        "refs": [
          {
            "field": "account",
            "many": true,
            "targets": [
              "account"
            ]
          },
          {
            "field": "agreement",
            "many": true,
            "targets": [
              "agreement"
            ]
          },
          {
            "field": "engagedParty",
            "many": false,
            "targets": [
              "individual",
              "organization"
            ]
          },
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "document-management",
    "tmf": "TMF667",
    "label": "Document Management",
    "group": "Other",
    "basePath": "/tmf-api/documentManagement/v4",
    "resources": [
      {
        "name": "document",
        "entityType": "Document",
        "urnType": null,
        "refs": []
      },
      {
        "name": "documentSpecification",
        "entityType": "DocumentSpecification",
        "urnType": "document-specification",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "party-catalog",
    "tmf": "TMF632",
    "label": "Party",
    "group": "Parties",
    "basePath": "/tmf-api/party/v4",
    "resources": [
      {
        "name": "individual",
        "entityType": "Individual",
        "urnType": "individual",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      },
      {
        "name": "organization",
        "entityType": "Organization",
        "urnType": "organization",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "party-role",
    "tmf": "TMF669",
    "label": "Party Role",
    "group": "Parties",
    "basePath": "/tmf-api/partyRole/v4",
    "resources": [
      {
        "name": "partyRole",
        "entityType": "PartyRole",
        "urnType": "party-role",
        "refs": [
          {
            "field": "account",
            "many": true,
            "targets": [
              "account"
            ]
          },
          {
            "field": "agreement",
            "many": true,
            "targets": [
              "agreement"
            ]
          },
          {
            "field": "engagedParty",
            "many": false,
            "targets": [
              "individual",
              "organization"
            ]
          },
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "product-catalog",
    "tmf": "TMF620",
    "label": "Product Catalog",
    "group": "Catalogue",
    "basePath": "/tmf-api/productCatalogManagement/v4",
    "resources": [
      {
        "name": "catalog",
        "entityType": "Catalog",
        "urnType": "catalog",
        "refs": [
          {
            "field": "category",
            "many": true,
            "targets": [
              "category"
            ]
          },
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      },
      {
        "name": "category",
        "entityType": "Category",
        "urnType": "category",
        "refs": [
          {
            "field": "parentId",
            "many": false,
            "targets": [
              "category"
            ]
          },
          {
            "field": "productOffering",
            "many": true,
            "targets": [
              "product-offering"
            ]
          },
          {
            "field": "subCategory",
            "many": true,
            "targets": [
              "category"
            ]
          }
        ]
      },
      {
        "name": "productOffering",
        "entityType": "ProductOffering",
        "urnType": "product-offering",
        "refs": [
          {
            "field": "agreement",
            "many": true,
            "targets": [
              "agreement"
            ]
          },
          {
            "field": "category",
            "many": true,
            "targets": [
              "category"
            ]
          },
          {
            "field": "channel",
            "many": true,
            "targets": [
              "channel"
            ]
          },
          {
            "field": "marketSegment",
            "many": true,
            "targets": [
              "market-segment"
            ]
          },
          {
            "field": "productOfferingPrice",
            "many": true,
            "targets": [
              "product-offering-price"
            ]
          },
          {
            "field": "productOfferingRelationship",
            "many": true,
            "targets": [
              "product-offering"
            ]
          },
          {
            "field": "productSpecification",
            "many": false,
            "targets": [
              "product-specification"
            ]
          },
          {
            "field": "resourceCandidate",
            "many": false,
            "targets": [
              "resource-candidate"
            ]
          },
          {
            "field": "serviceCandidate",
            "many": false,
            "targets": [
              "service-candidate"
            ]
          },
          {
            "field": "serviceLevelAgreement",
            "many": false,
            "targets": [
              "sla"
            ]
          }
        ]
      },
      {
        "name": "productOfferingPrice",
        "entityType": "ProductOfferingPrice",
        "urnType": "product-offering-price",
        "refs": [
          {
            "field": "popRelationship",
            "many": true,
            "targets": [
              "product-offering-price"
            ]
          }
        ]
      },
      {
        "name": "productSpecification",
        "entityType": "ProductSpecification",
        "urnType": "product-specification",
        "refs": [
          {
            "field": "productSpecificationRelationship",
            "many": true,
            "targets": [
              "product-specification"
            ]
          },
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          },
          {
            "field": "serviceSpecification",
            "many": true,
            "targets": [
              "service-specification"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "product-inventory",
    "tmf": "TMF637",
    "label": "Product Inventory",
    "group": "Inventory",
    "basePath": "/tmf-api/productInventory/v4",
    "resources": [
      {
        "name": "product",
        "entityType": "Product",
        "urnType": "product",
        "refs": [
          {
            "field": "agreement",
            "many": true,
            "targets": [
              "agreement"
            ]
          },
          {
            "field": "billingAccount",
            "many": false,
            "targets": [
              "billing-account"
            ]
          },
          {
            "field": "product",
            "many": true,
            "targets": [
              "product"
            ]
          },
          {
            "field": "productOffering",
            "many": false,
            "targets": [
              "product-offering"
            ]
          },
          {
            "field": "productOrderItem",
            "many": true,
            "targets": [
              "product-order"
            ]
          },
          {
            "field": "productSpecification",
            "many": false,
            "targets": [
              "product-specification"
            ]
          },
          {
            "field": "realizingService",
            "many": true,
            "targets": [
              "service"
            ]
          },
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "product-ordering-management",
    "tmf": "TMF622",
    "label": "Product Ordering",
    "group": "Ordering",
    "basePath": "/tmf-api/productOrderingManagement/v4",
    "resources": [
      {
        "name": "productOrder",
        "entityType": "ProductOrder",
        "urnType": "product-order",
        "refs": [
          {
            "field": "agreement",
            "many": true,
            "targets": [
              "agreement"
            ]
          },
          {
            "field": "billingAccount",
            "many": false,
            "targets": [
              "billing-account"
            ]
          },
          {
            "field": "payment",
            "many": true,
            "targets": [
              "payment"
            ]
          },
          {
            "field": "quote",
            "many": true,
            "targets": [
              "quote"
            ]
          },
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "quote",
    "tmf": "TMF648",
    "label": "Quote",
    "group": "Agreements",
    "basePath": "/tmf-api/quote/v4",
    "resources": [
      {
        "name": "quote",
        "entityType": "Quote",
        "urnType": "quote",
        "refs": [
          {
            "field": "agreement",
            "many": true,
            "targets": [
              "agreement"
            ]
          },
          {
            "field": "billingAccount",
            "many": true,
            "targets": [
              "billing-account"
            ]
          },
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "resource-catalog",
    "tmf": "TMF634",
    "label": "Resource Catalog",
    "group": "Catalogue",
    "basePath": "/tmf-api/resourceCatalog/v4",
    "resources": [
      {
        "name": "resourceCandidate",
        "entityType": "ResourceCandidate",
        "urnType": "resource-candidate",
        "refs": [
          {
            "field": "category",
            "many": true,
            "targets": [
              "resource-category"
            ]
          }
        ]
      },
      {
        "name": "resourceCatalog",
        "entityType": "ResourceCatalog",
        "urnType": "resource-catalog",
        "refs": [
          {
            "field": "category",
            "many": true,
            "targets": [
              "resource-category"
            ]
          },
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      },
      {
        "name": "resourceCategory",
        "entityType": "ResourceCategory",
        "urnType": "resource-category",
        "refs": [
          {
            "field": "category",
            "many": true,
            "targets": [
              "resource-category"
            ]
          },
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          },
          {
            "field": "resourceCandidate",
            "many": true,
            "targets": [
              "resource-candidate"
            ]
          }
        ]
      },
      {
        "name": "resourceSpecification",
        "entityType": "ResourceSpecification",
        "urnType": "resource-specification",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "resource-function-activation",
    "tmf": "TMF664",
    "label": "Resource Function Activation",
    "group": "Inventory",
    "basePath": "/tmf-api/resourceFunctionActivation/v4",
    "resources": [
      {
        "name": "resourceFunction",
        "entityType": "ResourceFunction",
        "urnType": "resource-function",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "resource-inventory",
    "tmf": "TMF639",
    "label": "Resource Inventory",
    "group": "Inventory",
    "basePath": "/tmf-api/resourceInventoryManagement/v4",
    "resources": [
      {
        "name": "resource",
        "entityType": "Resource",
        "urnType": "resource",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "resource-order-management",
    "tmf": "TMF652",
    "label": "Resource Ordering",
    "group": "Ordering",
    "basePath": "/tmf-api/resourceOrderingManagement/v4",
    "resources": [
      {
        "name": "resourceOrder",
        "entityType": "ResourceOrder",
        "urnType": "resource-order",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "service-catalog",
    "tmf": "TMF633",
    "label": "Service Catalog",
    "group": "Catalogue",
    "basePath": "/tmf-api/serviceCatalogManagement/v4",
    "resources": [
      {
        "name": "serviceCandidate",
        "entityType": "ServiceCandidate",
        "urnType": "service-candidate",
        "refs": [
          {
            "field": "category",
            "many": true,
            "targets": [
              "service-category"
            ]
          },
          {
            "field": "serviceSpecification",
            "many": false,
            "targets": [
              "service-specification"
            ]
          }
        ]
      },
      {
        "name": "serviceCatalog",
        "entityType": "ServiceCatalog",
        "urnType": "service-catalog",
        "refs": [
          {
            "field": "category",
            "many": true,
            "targets": [
              "service-category"
            ]
          },
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      },
      {
        "name": "serviceCategory",
        "entityType": "ServiceCategory",
        "urnType": "service-category",
        "refs": [
          {
            "field": "category",
            "many": true,
            "targets": [
              "service-category"
            ]
          },
          {
            "field": "parentId",
            "many": false,
            "targets": [
              "service-category"
            ]
          },
          {
            "field": "serviceCandidate",
            "many": true,
            "targets": [
              "service-candidate"
            ]
          }
        ]
      },
      {
        "name": "serviceSpecification",
        "entityType": "ServiceSpecification",
        "urnType": "service-specification",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          },
          {
            "field": "serviceLevelSpecification",
            "many": true,
            "targets": [
              "service-level-specification"
            ]
          },
          {
            "field": "serviceSpecRelationship",
            "many": true,
            "targets": [
              "service-specification"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "service-inventory",
    "tmf": "TMF638",
    "label": "Service Inventory",
    "group": "Inventory",
    "basePath": "/tmf-api/serviceInventory/v4",
    "resources": [
      {
        "name": "service",
        "entityType": "Service",
        "urnType": "service",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          },
          {
            "field": "serviceSpecification",
            "many": false,
            "targets": [
              "service-specification"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "service-order-management",
    "tmf": "TMF641",
    "label": "Service Ordering",
    "group": "Ordering",
    "basePath": "/tmf-api/serviceOrdering/v4",
    "resources": [
      {
        "name": "serviceOrder",
        "entityType": "ServiceOrder",
        "urnType": "service-order",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "software-management",
    "tmf": "TMF730",
    "label": "Software Compute",
    "group": "Other",
    "basePath": "/tmf-api/softwareCompute/v4",
    "resources": [
      {
        "name": "resource",
        "entityType": "Resource",
        "urnType": "resource",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      },
      {
        "name": "resourceSpecification",
        "entityType": "ResourceSpecification",
        "urnType": "resource-specification",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  },
  {
    "key": "usage-management",
    "tmf": "TMF635",
    "label": "Usage Management",
    "group": "Other",
    "basePath": "/tmf-api/usageManagement/v4",
    "resources": [
      {
        "name": "usage",
        "entityType": "Usage",
        "urnType": "usage",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          },
          {
            "field": "usageSpecification",
            "many": false,
            "targets": [
              "usageSpecification"
            ]
          }
        ]
      },
      {
        "name": "usageSpecification",
        "entityType": "UsageSpecification",
        "urnType": "usageSpecification",
        "refs": [
          {
            "field": "relatedParty",
            "many": true,
            "targets": [
              "individual",
              "organization"
            ]
          }
        ]
      }
    ]
  }
];
