apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: shared-alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    cert-manager.io/cluster-issuer: prod
    cert-manager.io/common-name: tir.dsc.edhia.eu
    cert-manager.io/private-key-algorithm: ECDSA
    meta.helm.sh/release-name: trust-anchor
    meta.helm.sh/release-namespace: trust-anchor
  creationTimestamp: "2026-03-02T08:12:17Z"
  finalizers:
  - group.ingress.k8s.aws/shared-alb
  generation: 2
  labels:
    app.kubernetes.io/instance: trust-anchor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trusted-issuers-list
    app.kubernetes.io/version: 0.7.0
    helm.sh/chart: trusted-issuers-list-0.15.0
  name: tir-tir
  namespace: trust-anchor
  resourceVersion: "1265810"
  uid: c7c7d3bb-8928-4042-b4f6-ca0e27547091
spec:
  ingressClassName: alb
  rules:
  - host: tir.dsc.edhia.eu
    http:
      paths:
      - backend:
          service:
            name: tir
            port:
              number: 8080
        path: /v4/issuers
        pathType: Prefix
  tls:
  - hosts:
    - tir.dsc.edhia.eu
    secretName: tir.dsc.edhia.eu-tls
status:
  loadBalancer:
    ingress:
    - hostname: k8s-sharedalb-8a9991180c-1072230074.eu-west-1.elb.amazonaws.com
      ports:
      - port: 80
        protocol: ""
