micronaut:

  server:
    port: 8632

  metrics:
    enabled: true
    export:
      prometheus:
        step: PT2s
        descriptions: false

  http:
    services:
      read-timeout: 30s
      ngsi:
        path: ngsi-ld/v1
        url: http://localhost:1026
        read-timeout: 30
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
---
endpoints:
  metrics:
    enabled: true
  health:
    enabled: true

---
loggers:
  levels:
    ROOT: WARN

---
general:
  contextUrl: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
  serverHost: http://localhost:8632

apiExtension:
  # we reference the env var here directly, since property resolution from env vars happens AFTER evaluation of @Requires
  # and therefor would not be possible through env-vars else
  enabled: ${API_EXTENSION_ENABLED}