---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api
spec:
  type: LoadBalancer
  ports:
    - port: 8632
      targetPort: 8632
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: api
    spec:
      serviceAccountName: default
      containers:
        - name: api
          imagePullPolicy: Never
          image: "api"
          ports:
            - name: http
              containerPort: 8632
              protocol: TCP
          env:
            - name: MICRONAUT_HTTP_SERVICES_NGSI_URL
              value: http://orion-ld:1026
            - name: GENERAL_BASEPATH
              value: ${module.ctk.base-path}